version: '3'

services:
  user-service:
    build: ./user-service
    ports:
      - "50051:50051"
    depends_on:
      - userdb

  userdb:
    image: postgres:alpine
    environment:
      POSTGRES_DB: userdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"

  car-service:
    build: ./car-service
    ports:
      - "50052:50052"
    depends_on:
      - cardb

  cardb:
    image: postgres:alpine
    environment:
      POSTGRES_DB: cardb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    ports:
      - "5433:5432"

  booking-service:
    build: ./booking-service
    ports:
      - "50053:50053"
    depends_on:
      - bookingdb

  bookingdb:
    image: postgres:alpine
    environment:
      POSTGRES_DB: bookingdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    ports:
      - "5434:5432"

  gateway:
    build: ./gateway
    ports:
      - "8080:8080"
    depends_on:
      - user-service
      - car-service
      - booking-service
